import { ElementRef, AfterViewInit } from '@angular/core';
import { BaseChartComponent } from '../common/base-chart.component';
import { ColorHelper } from '../common/color.helper';
import { ViewDimensions } from '../common/view-dimensions.helper';
export declare class PowerGaugeComponent extends BaseChartComponent implements AfterViewInit {
    min: number;
    max: number;
    units: string;
    results: any[];
    axisPoints: any[];
    pointerValue: number;
    showAxis: boolean;
    activeEntries: any[];
    axisTickFormatting: any;
    margin: any[];
    textEl: ElementRef;
    colors: ColorHelper;
    dims: ViewDimensions;
    domain: any[];
    valueDomain: any;
    valueScale: any;
    arcSet: any;
    axisValues: any;
    transform: string;
    displayValue: string;
    innerRadius: number;
    outerRadius: number;
    textRadius: number;
    resizeScale: number;
    textTransform: string;
    cornerRadius: number;
    startAngle: number;
    pointerAngle: number;
    endAngle: number;
    angleSpan: number;
    ngAfterViewInit(): void;
    update(): void;
    getArcSet(): any;
    getAxisValues(): any;
    getTextAnchor(angle: any): string;
    getDomain(): any[];
    getValueDomain(): any[];
    getValueScale(): any;
    setColors(): void;
    getDisplayValue(): string;
}
